import { getConfig } from './config.js';

// Philips Hue local bridge API. HUE_USERNAME is the API key generated by
// pairing with the bridge (press the physical button, then POST /api to
// create a user) — a one-time manual step, documented in the README.
export class HueSync {
  get configured() {
    const c = getConfig();
    return !!(c.HUE_BRIDGE_IP && c.HUE_USERNAME && c.HUE_LIGHT_ID);
  }

  // Standard Philips-documented sRGB -> CIE xy conversion.
  rgbToXy(r, g, b) {
    const toLinear = (c) => {
      c /= 255;
      return c > 0.04045 ? Math.pow((c + 0.055) / 1.055, 2.4) : c / 12.92;
    };
    const R = toLinear(r);
    const G = toLinear(g);
    const B = toLinear(b);

    const X = R * 0.664511 + G * 0.154324 + B * 0.162028;
    const Y = R * 0.283881 + G * 0.668433 + B * 0.047685;
    const Z = R * 0.000088 + G * 0.072310 + B * 0.986039;

    const sum = X + Y + Z;
    if (sum === 0) return [0, 0];
    return [X / sum, Y / sum];
  }

  async setColor(r, g, b) {
    if (!this.configured) return;
    const { HUE_BRIDGE_IP, HUE_USERNAME, HUE_LIGHT_ID } = getConfig();
    const [x, y] = this.rgbToXy(r, g, b);
    const url = `http://${HUE_BRIDGE_IP}/api/${HUE_USERNAME}/lights/${HUE_LIGHT_ID}/state`;
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), 10_000);
    try {
      const res = await fetch(url, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ on: true, xy: [x, y] }),
        signal: controller.signal,
      });
      if (!res.ok) console.error(`[hue] ${res.status} ${res.statusText}`);
    } catch (err) {
      console.error('[hue] request failed:', err.message);
    } finally {
      clearTimeout(timer);
    }
  }
}
